---
name: Close stale issues and PRs
on:
  schedule:
    - cron: 30 * * * *

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          stale-issue-label: stale
          stale-pr-label: stale
